server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - name: RateLimiterGatewayFilter

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthGatewayFilter
            - name: RateLimiterGatewayFilter

        - id: image-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/images/**
          filters:
            - name: JwtAuthGatewayFilter
            - name: RateLimiterGatewayFilter

        - id: comment-like-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/comments/**,/api/likes/**
          filters:
            - name: JwtAuthGatewayFilter
            - name: RateLimiterGatewayFilter

  jwt:
    secret: "mySuperSecretKeyForJWTTokenGenerationAndValidationInSpringMicroserviceCourse2023"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    by.losik.apigateway: DEBUG

---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  data:
    redis:
      host: redis-service
      port: 6379
