spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/activity_db}
      database: activity_db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      activity-events: activity-events

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.shell: INFO
    by.losik.activityservice: DEBUG

server:
  port: 8085