spring:
  application:
    name: image-service

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/spring_microservice_course_db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_microservice_course_db}

  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      password: ""
      database: 0
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_microservice_course_db}
    username: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    driver-class-name: org.postgresql.Driver

  aop:
    auto: true
    proxy-target-class: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    liquibase: INFO
    by.losik.imageservice: DEBUG
    software.amazon.awssdk: DEBUG

server:
  port: 8082
